project_id = "btieehbdvyghccpzftge"

[functions.send-email]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.generate-driver]
verify_jwt = true

[functions.fetch-html]
verify_jwt = false

[functions.extract-video-data]
verify_jwt = true

[functions.extract-anime-data]
verify_jwt = true

[functions.crawl-episodes]
verify_jwt = true

[functions.ai-recommendations]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true